<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Preetijaiswal-IT" failures="2" tests="4" name="Test" time="0.245" errors="0" timestamp="2023-03-10T14:29:15 IST">
  <testcase classname="allure.TestCase" name="failTest" time="0.091">
    <failure type="java.lang.AssertionError" message="Failed due to 404 page">
      <![CDATA[java.lang.AssertionError: Failed due to 404 page
at allure.TestCase.failTest(TestCase.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase classname="allure.TestCase" name="doLogin" time="0.005"/>
  <testcase classname="allure.TestCase" name="doSignUp" time="0.004">
    <failure type="java.lang.AssertionError" message="Signup is failed">
      <![CDATA[java.lang.AssertionError: Signup is failed
at allure.TestCase.doSignUp(TestCase.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- doSignUp -->
  <testcase classname="allure.TestCase" name="homePage" time="0.004">
    <skipped/>
  </testcase> <!-- homePage -->
</testsuite> <!-- Test -->
