<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Preetijaiswal-IT" failures="2" tests="8" name="Test" time="0.064" errors="0" timestamp="2022-03-09T11:51:17 IST">
  <testcase classname="com.retryanalyzer.MyTest" name="Test1" time="0.008">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.retryanalyzer.MyTest" name="Test1" time="0.0">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.retryanalyzer.MyTest" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="com.retryanalyzer.MyTest" name="Test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.retryanalyzer.MyTest.Test1(MyTest.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="com.retryanalyzer.MyTest" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="com.retryanalyzer.MyTest" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="com.retryanalyzer.MyTest" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="com.retryanalyzer.MyTest" name="Test2" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.retryanalyzer.MyTest.Test2(MyTest.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- Test -->
